### ISSUE TITLE
前端还会优化吗？

### ISSUE THREAD

**Issue by cfkka** [Yufccode/Load-balanced-online-OJ-system#3]
前端还会优化，或者添加新功能吗？

**Comment by ffengc** [comment]
感谢你的对这个项目的关注。暂时不会继续优化了，这个项目主要是后端部分的搭建。前端如果大家有更好的优化方案可以直接fork然后优化。后端我后续有可能会换成reactor模式的服务器来代替这个httplib第三方库。

**Comment by cfkka** [comment]
好的
